#!/bin/bash

# Check that we don't get debug symbols [#@] on some test texts.

set -e -u

cd "$(dirname "$0")"


out=$(mktemp -t hash-count-swe-dan.XXXXXXXXXX)
trap 'rm -f "${out}"' EXIT

cat ../texts/*.swe.txt | apertium -f html-noent -d .. swe-dan > "${out}"

current=$(grep -c '[#@]' "${out}" || true)

if [[ "${current}" -gt 0 ]]; then
    echo "ERROR: texts/*.swe.txt translated through swe-dan gave debug sybols [#@]:"
    grep -n '[#@]' "${out}"
    exit 1
fi
